services:
  report-db:
    image: postgres:16-alpine
    container_name: report-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: report
      POSTGRES_PASSWORD: report_password
      POSTGRES_DB: reporting_db
    ports:
      - "5433:5432"
    volumes:
      - report_postgres_data:/var/lib/postgresql/data

  auth-db:
    image: postgres:16-alpine
    container_name: auth-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: super_secure
      POSTGRES_DB: auth_db
    ports:
      - "5444:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

volumes:
  report_postgres_data:
  auth_postgres_data:
